// TODO: UPDATE BEFORE RELEASE

// KILT Blockchain – https://botlabs.org
// Copyright (C) 2019-2023 BOTLabs GmbH

// The KILT Blockchain is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// The KILT Blockchain is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// If you feel like getting in touch with us, you can do so at info@botlabs.org

//! Autogenerated weights for `pallet_did_lookup`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-05, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rust-2`, CPU: `12th Gen Intel(R) Core(TM) i9-12900K`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/kilt-parachain
// benchmark
// pallet
// --template=.maintain/runtime-weight-template.hbs
// --header=HEADER-GPL
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --steps=2
// --repeat=1
// --chain=dev
// --pallet=pallet-did-lookup
// --extrinsic=*
// --output=./runtimes/peregrine/src/weights/pallet_did_lookup.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_did_lookup`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_did_lookup::WeightInfo for WeightInfo<T> {
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(132), added: 2607, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedDids (r:1 w:1)
	/// Proof: DidLookup ConnectedDids (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedAccounts (r:0 w:2)
	/// Proof: DidLookup ConnectedAccounts (max_values: None, max_size: Some(97), added: 2572, mode: MaxEncodedLen)
	fn associate_account_multisig_sr25519() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `5211`
		// Minimum execution time: 70_942_000 picoseconds.
		Weight::from_parts(70_942_000, 0)
			.saturating_add(Weight::from_parts(0, 5211))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(132), added: 2607, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedDids (r:1 w:1)
	/// Proof: DidLookup ConnectedDids (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedAccounts (r:0 w:2)
	/// Proof: DidLookup ConnectedAccounts (max_values: None, max_size: Some(97), added: 2572, mode: MaxEncodedLen)
	fn associate_account_multisig_ed25519() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `5211`
		// Minimum execution time: 66_569_000 picoseconds.
		Weight::from_parts(66_569_000, 0)
			.saturating_add(Weight::from_parts(0, 5211))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(132), added: 2607, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedDids (r:1 w:1)
	/// Proof: DidLookup ConnectedDids (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedAccounts (r:0 w:2)
	/// Proof: DidLookup ConnectedAccounts (max_values: None, max_size: Some(97), added: 2572, mode: MaxEncodedLen)
	fn associate_account_multisig_ecdsa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `5211`
		// Minimum execution time: 71_977_000 picoseconds.
		Weight::from_parts(71_977_000, 0)
			.saturating_add(Weight::from_parts(0, 5211))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(132), added: 2607, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedDids (r:1 w:1)
	/// Proof: DidLookup ConnectedDids (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedAccounts (r:0 w:2)
	/// Proof: DidLookup ConnectedAccounts (max_values: None, max_size: Some(97), added: 2572, mode: MaxEncodedLen)
	fn associate_eth_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `437`
		//  Estimated: `5211`
		// Minimum execution time: 68_618_000 picoseconds.
		Weight::from_parts(68_618_000, 0)
			.saturating_add(Weight::from_parts(0, 5211))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(132), added: 2607, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedDids (r:1 w:1)
	/// Proof: DidLookup ConnectedDids (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedAccounts (r:0 w:2)
	/// Proof: DidLookup ConnectedAccounts (max_values: None, max_size: Some(97), added: 2572, mode: MaxEncodedLen)
	fn associate_sender() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `5211`
		// Minimum execution time: 33_964_000 picoseconds.
		Weight::from_parts(33_964_000, 0)
			.saturating_add(Weight::from_parts(0, 5211))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: DidLookup ConnectedDids (r:1 w:1)
	/// Proof: DidLookup ConnectedDids (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(132), added: 2607, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedAccounts (r:0 w:1)
	/// Proof: DidLookup ConnectedAccounts (max_values: None, max_size: Some(97), added: 2572, mode: MaxEncodedLen)
	fn remove_sender_association() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `5211`
		// Minimum execution time: 20_715_000 picoseconds.
		Weight::from_parts(20_715_000, 0)
			.saturating_add(Weight::from_parts(0, 5211))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: DidLookup ConnectedDids (r:1 w:1)
	/// Proof: DidLookup ConnectedDids (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(132), added: 2607, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedAccounts (r:0 w:1)
	/// Proof: DidLookup ConnectedAccounts (max_values: None, max_size: Some(97), added: 2572, mode: MaxEncodedLen)
	fn remove_account_association() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `5211`
		// Minimum execution time: 19_749_000 picoseconds.
		Weight::from_parts(19_749_000, 0)
			.saturating_add(Weight::from_parts(0, 5211))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: DidLookup ConnectedDids (r:1 w:1)
	/// Proof: DidLookup ConnectedDids (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(132), added: 2607, mode: MaxEncodedLen)
	fn change_deposit_owner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `862`
		//  Estimated: `7818`
		// Minimum execution time: 27_037_000 picoseconds.
		Weight::from_parts(27_037_000, 0)
			.saturating_add(Weight::from_parts(0, 7818))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: DidLookup ConnectedDids (r:1 w:1)
	/// Proof: DidLookup ConnectedDids (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(132), added: 2607, mode: MaxEncodedLen)
	fn update_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `5211`
		// Minimum execution time: 23_615_000 picoseconds.
		Weight::from_parts(23_615_000, 0)
			.saturating_add(Weight::from_parts(0, 5211))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: DidLookup MigrationStateStore (r:1 w:1)
	/// Proof: DidLookup MigrationStateStore (max_values: Some(1), max_size: Some(35), added: 530, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedDids (r:101 w:184)
	/// Proof: DidLookup ConnectedDids (max_values: None, max_size: Some(129), added: 2604, mode: MaxEncodedLen)
	/// Storage: DidLookup ConnectedAccounts (r:92 w:184)
	/// Proof: DidLookup ConnectedAccounts (max_values: None, max_size: Some(97), added: 2572, mode: MaxEncodedLen)
	/// The range of component `n` is `[1, 100]`.
	fn migrate(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2127 + n * (324 ±0)`
		//  Estimated: `500158`
		// Minimum execution time: 62_088_000 picoseconds.
		Weight::from_parts(1_119_084_000, 0)
			.saturating_add(Weight::from_parts(0, 500158))
			.saturating_add(T::DbWeight::get().reads(194))
			.saturating_add(T::DbWeight::get().writes(369))
	}
}

#[cfg(test)]
mod tests {
	#[test]
	fn test_associate_account_multisig_sr25519() {
		assert!(
			<crate::Runtime as frame_system::Config>::BlockWeights::get()
				.per_class
				.get(frame_support::dispatch::DispatchClass::Normal)
				.max_extrinsic
				.unwrap_or_else(<sp_weights::Weight as sp_runtime::traits::Bounded>::max_value)
				.proof_size()
				> 5211
		);
	}
	#[test]
	fn test_associate_account_multisig_ed25519() {
		assert!(
			<crate::Runtime as frame_system::Config>::BlockWeights::get()
				.per_class
				.get(frame_support::dispatch::DispatchClass::Normal)
				.max_extrinsic
				.unwrap_or_else(<sp_weights::Weight as sp_runtime::traits::Bounded>::max_value)
				.proof_size()
				> 5211
		);
	}
	#[test]
	fn test_associate_account_multisig_ecdsa() {
		assert!(
			<crate::Runtime as frame_system::Config>::BlockWeights::get()
				.per_class
				.get(frame_support::dispatch::DispatchClass::Normal)
				.max_extrinsic
				.unwrap_or_else(<sp_weights::Weight as sp_runtime::traits::Bounded>::max_value)
				.proof_size()
				> 5211
		);
	}
	#[test]
	fn test_associate_eth_account() {
		assert!(
			<crate::Runtime as frame_system::Config>::BlockWeights::get()
				.per_class
				.get(frame_support::dispatch::DispatchClass::Normal)
				.max_extrinsic
				.unwrap_or_else(<sp_weights::Weight as sp_runtime::traits::Bounded>::max_value)
				.proof_size()
				> 5211
		);
	}
	#[test]
	fn test_associate_sender() {
		assert!(
			<crate::Runtime as frame_system::Config>::BlockWeights::get()
				.per_class
				.get(frame_support::dispatch::DispatchClass::Normal)
				.max_extrinsic
				.unwrap_or_else(<sp_weights::Weight as sp_runtime::traits::Bounded>::max_value)
				.proof_size()
				> 5211
		);
	}
	#[test]
	fn test_remove_sender_association() {
		assert!(
			<crate::Runtime as frame_system::Config>::BlockWeights::get()
				.per_class
				.get(frame_support::dispatch::DispatchClass::Normal)
				.max_extrinsic
				.unwrap_or_else(<sp_weights::Weight as sp_runtime::traits::Bounded>::max_value)
				.proof_size()
				> 5211
		);
	}
	#[test]
	fn test_remove_account_association() {
		assert!(
			<crate::Runtime as frame_system::Config>::BlockWeights::get()
				.per_class
				.get(frame_support::dispatch::DispatchClass::Normal)
				.max_extrinsic
				.unwrap_or_else(<sp_weights::Weight as sp_runtime::traits::Bounded>::max_value)
				.proof_size()
				> 5211
		);
	}
	#[test]
	fn test_change_deposit_owner() {
		assert!(
			<crate::Runtime as frame_system::Config>::BlockWeights::get()
				.per_class
				.get(frame_support::dispatch::DispatchClass::Normal)
				.max_extrinsic
				.unwrap_or_else(<sp_weights::Weight as sp_runtime::traits::Bounded>::max_value)
				.proof_size()
				> 7818
		);
	}
	#[test]
	fn test_update_deposit() {
		assert!(
			<crate::Runtime as frame_system::Config>::BlockWeights::get()
				.per_class
				.get(frame_support::dispatch::DispatchClass::Normal)
				.max_extrinsic
				.unwrap_or_else(<sp_weights::Weight as sp_runtime::traits::Bounded>::max_value)
				.proof_size()
				> 5211
		);
	}
	#[test]
	fn test_migrate() {
		assert!(
			<crate::Runtime as frame_system::Config>::BlockWeights::get()
				.per_class
				.get(frame_support::dispatch::DispatchClass::Normal)
				.max_extrinsic
				.unwrap_or_else(<sp_weights::Weight as sp_runtime::traits::Bounded>::max_value)
				.proof_size()
				> 500158
		);
	}
}
