#!/bin/sh
set -e

DAEMON_CONF="/etc/default/mashnet-node"

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -f ${DAEMON_CONF} ]; then
        rm ${DAEMON_CONF}
    fi
    ;;
esac

#DEBHELPER#
